'use strict';
(async()=>{
 const stage=new URLSearchParams(location.search).get('stage')||'about',host=document.querySelector('#content');
 document.querySelector(`[data-stage="${['furnish','cameras','images','videos'].includes(stage)?stage:'plan'}"]`)?.setAttribute('aria-current','page');
 const matrix=`<table><thead><tr><th>Function</th><th>Preview behavior</th><th>Backend status</th></tr></thead><tbody><tr><td>Plan, wall/opening edits, elevation, units, undo/redo</td><td>Working browser editor using the application's geometry code. Demonstration dimensions only.</td><td>No live backend</td></tr><tr><td>Surface Design</td><td>Working 2D placement, sizes and finishes. Browser-local save.</td><td>No live backend</td></tr><tr><td>Save/reopen</td><td>Mock API adapter stores this synthetic draft in your browser. Other visitors have separate data.</td><td>Mocked; not server persistence or authentication</td></tr><tr><td>Joined wall fills</td><td>Original fixture uses offline Python output. Edited fills use simplified browser rectangles; corner topology editing still uses real client logic.</td><td>Production polygon validation unavailable</td></tr><tr><td>3D / Furnish / Cameras</td><td>Read-only synthetic 3D fixture prepared offline by the real geometry backend. Orbit and zoom work. Furnishing placement and camera saving are unavailable.</td><td>No live rebuild. Changed architecture cannot be presented as current 3D.</td></tr><tr><td>Imports, uploads, references, product lookup</td><td>Unavailable. Do not enter private project information in this public demo.</td><td>No upload or external lookup service</td></tr><tr><td>Image / video generation and approvals</td><td>Unavailable; zero attempts and no generated output. Existing generation allowances are untouched.</td><td>No inference, job queue or approval API</td></tr><tr><td>PC / worker management</td><td>Not included.</td><td>No management endpoints, credentials or connection</td></tr></tbody></table>`;
 const [seed,scene]=await Staging.ready,current=await Staging.load(),stale=Staging.shape(seed)!==Staging.shape(current);
 if(stage==='images'||stage==='videos'){
  host.innerHTML=`<span class="tag">UNAVAILABLE · NO BACKEND</span><h1>${stage==='images'?'Images':'Video'}</h1><div class="blocked"><h2>Generation is not enabled in staging</h2><p>This public preview has no renderer, worker connection, generation queue or approval controls. No image or video will be submitted, including when browsing these screens.</p><p>Image attempts: 0 · Video attempts: 0 · Reference generation: 0</p><p>These are preview limits only. Your actual project and its allowances are unchanged.</p><a href="?stage=about">View all capabilities and limitations →</a></div>`;return;
 }
 if(!['furnish','cameras'].includes(stage)){
  host.innerHTML=`<span class="tag">PUBLIC HTTPS PREVIEW · SYNTHETIC DATA ONLY</span><h1>Your studio, safely in the browser.</h1><p class="muted">Explore an invented 8 × 5.5 metre apartment. This is an isolated preview of Pixeloid's browser editor, not a connection to your Mac or PC.</p><div class="cards"><section class="card"><h2>Try the working editor</h2><p>Move walls, edit openings, use elevation, test units and undo, or place finishes in Surface Design. Save and reopen within this browser.</p><a class="primary" href="app/floor-plan.html#synthetic-apartment-v1">Open synthetic Plan →</a></section><section class="card"><h2>Inspect the 3D fixture</h2><p>Orbit a synthetic apartment prepared offline with the real geometry code. Live backend rebuilding, furniture placement and generation are unavailable.</p><a class="primary" href="?stage=furnish">View synthetic 3D →</a></section></div><h2>What is real, mocked or unavailable?</h2>${matrix}<p class="muted">No sign-in is required. Reset demo clears only this browser's synthetic draft. No private apartment, uploaded plan, reference image, output, worker credential or PC endpoint is included.</p>`;return;
 }
 host.innerHTML=`<span class="tag">READ-ONLY FIXTURE · NOT A LIVE BACKEND</span><h1>${stage==='cameras'?'Cameras':'Furnish'}</h1><p>${stale?'Your saved Plan has changed. The 3D below is the original fixture, not your edited plan. Live rebuilding is unavailable.':'This is the original synthetic apartment fixture. Its geometry was prepared offline by the real backend.'} Orbit and zoom are local viewing controls; ${stage==='cameras'?'camera saving':'furniture placement'} is unavailable.</p><div class="preview-grid"><section><h2>Saved synthetic Plan ${stale?'· edited':''}</h2><svg id="overview" class="viewport" viewBox="0 0 940 700" aria-label="Saved synthetic apartment plan"></svg></section><section><h2>Original synthetic 3D · read-only</h2><canvas id="overview-3d" class="viewport" aria-label="Read-only synthetic 3D fixture"></canvas><div class="toolrow"><button id="fit3d">Fit</button><button id="top3d">Top</button><button id="projection3d">Toggle perspective</button></div></section></div><p><a href="app/floor-plan.html#synthetic-apartment-v1">Edit the Plan →</a> · <a href="?stage=about">Capabilities & limits</a></p>`;
 const svg=document.querySelector('#overview'),ns='http://www.w3.org/2000/svg';
 for(const f of current.features){const line=document.createElementNS(ns,'line');for(const [k,v] of Object.entries({x1:f.points[0][0],y1:f.points[0][1],x2:f.points[1][0],y2:f.points[1][1],stroke:f.kind==='wall'?'#8299a8':f.kind==='window'?'#2593a8':'#b28745','stroke-width':f.thickness}))line.setAttribute(k,v);svg.append(line)}
 const view={...BlockModelViewer.defaults(),transparent:false,zoom:1.2},viewer=new BlockModelViewer.Viewer(document.querySelector('#overview-3d'),view,()=>{});
 const faces=scene.surfaces.filter(f=>!f.ceiling).map(f=>({...f,color:'#'+f.color.map(v=>Math.round(v).toString(16).padStart(2,'0')).join(''),architecture:true}));viewer.update(faces);
 document.querySelector('#fit3d').onclick=()=>viewer.reset();document.querySelector('#top3d').onclick=()=>viewer.reset('top');document.querySelector('#projection3d').onclick=()=>{view.projection=view.projection==='perspective'?'orthographic':'perspective';viewer.draw()};
})().catch(e=>document.querySelector('#content').textContent='Preview could not load: '+e.message);
