const assert=require('node:assert/strict');
const {readImageDrop,validateReferenceFile,studioDropSource,uploadDestination}=require('../static/reference-upload.js');
const photo={name:'chair.png',size:1600,type:'image/png'};
assert.deepEqual(readImageDrop({files:[photo],items:[{kind:'file',getAsFile:()=>photo}]}).files,[photo],'A file represented twice by the browser uploads once');
assert.deepEqual(readImageDrop({files:[],items:[{kind:'file',getAsFile:()=>photo}]}).files,[photo],'Accept file items when FileList is empty');
assert.throws(()=>studioDropSource(readImageDrop({files:[],getData:()=>''}).source,'http://127.0.0.1:8777'),/No image file/,'Empty drops cannot report success');
const link=readImageDrop({files:[],getData:type=>type==='text/uri-list'?'# image\r\nhttp://127.0.0.1:8777/media/abc123':''});
assert.equal(studioDropSource(link.source,'http://127.0.0.1:8777'),'http://127.0.0.1:8777/media/abc123');
assert.equal(studioDropSource('https://example.com/image.png','http://127.0.0.1:8777'),'https://example.com/image.png','Website images route through the public image importer');
assert.throws(()=>studioDropSource('file:///C:/photo.png','http://127.0.0.1:8777'),/image link/,'No arbitrary local path reading');
assert.equal(validateReferenceFile(photo,'reference'),'');
assert.match(validateReferenceFile({name:'empty.png',size:0,type:'image/png'},'reference'),/empty/);
assert.match(validateReferenceFile({name:'large.png',size:33*1024*1024,type:'image/png'},'reference'),/32 MB/);
assert.match(validateReferenceFile({name:'notes.txt',size:400,type:'text/plain'},'reference'),/image file/);
assert.equal(validateReferenceFile({name:'plan.pdf',size:400,type:'application/pdf'},'plan'),'');
assert.match(validateReferenceFile({name:'plan.pdf',size:400,type:'application/pdf'},'reference'),/image file/);
const destination=uploadDestination({kind:'reference'},'project-a','room-a');
assert.deepEqual(uploadDestination(destination,'project-b','room-b'),destination,'Changing the visible room cannot redirect a queued multi-file upload');
global.DOMParser=class{parseFromString(){return {querySelector:()=>({getAttribute:key=>key==='src'?'https://images.example.com/small.jpg':key==='srcset'?'https://images.example.com/small.jpg 100w, https://images.example.com/full.jpg 1600w':null})}}};
const wrapped=readImageDrop({files:[],getData:type=>type==='text/html'?'<a href="https://shop.example.com/product"><img></a>':type==='text/uri-list'?'https://shop.example.com/product':''});
assert.equal(wrapped.source,'https://images.example.com/full.jpg','Prefer the image and its largest supplied size over a product page link');
delete global.DOMParser;
assert.equal(validateReferenceFile({name:'plan.DXF',size:400,type:'application/octet-stream'},'plan'),'');
assert.match(validateReferenceFile({name:'plan.dwg',size:400,type:'application/octet-stream'},'plan'),/unsupported/);
console.log('16 reference upload regression checks passed');
