const assert=require('assert'),fs=require('fs'),vm=require('vm');
let sequence=0;
const input={value:'4'},svg={querySelector:()=>null,querySelectorAll:()=>[],insertAdjacentHTML(){},getScreenCTM:()=>({a:2,inverse:()=>({})}),setPointerCapture(){},hasPointerCapture:()=>false};
const context={window:{},structuredClone,crypto:{randomUUID:()=>String(++sequence)},DrawingGeometry:require('../static/drawing-geometry.js'),document:{querySelector:()=>input,querySelectorAll:()=>[]},DOMPoint:class{constructor(x,y){this.x=x;this.y=y}matrixTransform(){return this}}};
vm.createContext(context);vm.runInContext(fs.readFileSync('static/plan-walls.js','utf8'),context);
const doc={width:400,height:200,revision:2,map_revision:4,site:{},edits:{},elements:[],features:[{id:'newwall',kind:'wall',points:[[20,20],[120,20]],thickness:2}]};
const walls=new context.window.PlanWalls(doc,{svg:()=>svg,changed(){},select(){},redraw(){},error:message=>{throw Error(message)}});
const event=(x,y,handle)=>({button:0,clientX:x,clientY:y,pointerId:1,target:{closest:selector=>selector==='[data-wall-handle]'&&handle?{dataset:{wallHandle:handle}}:null}});
walls.selected='newwall';walls.pointerDown(event(120,20,'1'));walls.pointerMove(event(150,40,'1'));walls.pointerUp(event(150,40,'1'));
assert.deepEqual(Array.from(walls.geometry().points[1]),[150,20]);assert.equal(walls.history.length,1);
walls.action('undo');assert.deepEqual(Array.from(doc.features[0].points[1]),[120,20]);
walls.action('redo');walls.selected='newwall';assert.equal(walls.geometry().points[1][0],150);
walls.pointerDown(event(85,21,'thickness'));walls.pointerMove(event(85,24,'thickness'));walls.pointerUp(event(85,24,'thickness'));assert.equal(walls.geometry().thickness,8);
walls.action('split');walls.pointerDown(event(80,20));assert.equal(doc.features.length,2);assert.equal(doc.features[0].points[1][0],80);
walls.action('insert-window');walls.pointerDown(event(40,20));walls.pointerDown(event(60,20));assert.equal(doc.features.filter(f=>f.kind==='wall').length,3);assert.equal(walls.source().kind,'window');
walls.action('remove');assert.equal(doc.features.filter(f=>f.kind==='window').length,0);walls.action('undo');assert.equal(doc.features.filter(f=>f.kind==='window').length,1);
walls.clear();walls.tool='wall';walls.pointerDown(event(30,60));assert.throws(()=>walls.payload(),/Finish/);walls.pointerDown(event(130,62));assert.equal(walls.geometry().points[1][1],60);
walls.pointerDown(event(130,60,'1'));walls.pointerMove(event(160,60,'1'));walls.pointerUp(event(160,60,'1'),true);assert.equal(walls.geometry().points[1][0],130);
console.log('Inline walls: anchored resize, thickness, split, window cutout, delete/undo, drawing and cancel passed');
// Added openings cut their host walls in one undoable edit.
const fresh={width:400,height:200,edits:{},features:[{id:'host',kind:'wall',points:[[20,100],[220,100]],thickness:4}],elements:[]};
const auto=new context.window.PlanWalls(fresh,{svg:()=>svg,changed(){},select(){},redraw(){},error:message=>{throw Error(message)}});
auto.tool='window';auto.pointerDown(event(60,102));auto.pointerDown(event(100,101));
assert.equal(fresh.features.filter(f=>f.kind==='wall').length,2);assert.equal(fresh.features.filter(f=>f.kind==='window').length,1);
assert.deepEqual(Array.from(auto.source().points[0]),[60,100]);assert.equal(auto.history.length,1);
auto.action('undo');assert.equal(fresh.features.length,1);assert.equal(fresh.features[0].id,'host');
auto.tool='sliding_door';auto.pointerDown(event(140,101));auto.pointerDown(event(200,99));
assert.equal(fresh.features.filter(f=>f.kind==='wall').length,2);assert.equal(auto.source().kind,'sliding_door');
assert.equal(auto.source().points[1][1],100);auto.action('undo');assert.equal(fresh.features.length,1);
auto.snapping=false;auto.tool='window';auto.pointerDown(event(60,120));auto.pointerDown(event(100,120));assert.equal(fresh.features.filter(f=>f.kind==='wall').length,1,'A detached opening does not split a distant wall');
console.log('Automatic window/slider insertion, host snapping, detached placement and single-step undo passed');
const beforeTransform=JSON.stringify(auto.source());auto.action('rotate-left');auto.action('rotate-right');assert.equal(JSON.stringify(auto.source()),beforeTransform);
auto.action('flip-x');auto.action('flip-x');assert.equal(JSON.stringify(auto.source()),beforeTransform);
const sourceId=auto.selected;auto.action('duplicate');assert.notEqual(auto.selected,sourceId);assert.equal(fresh.features.length,3);auto.action('undo');assert.equal(fresh.features.length,2);
fresh.features.push({id:'newdoor',kind:'door',points:[[100,100],[120,100]],thickness:1,flip:false});auto.selected='newdoor';auto.action('flip-y');assert.equal(auto.source().flip,true);auto.action('flip-y');assert.equal(auto.source().flip,false);
console.log('Architecture rotate, mirror, duplicate and undo passed');
