const assert=require('node:assert/strict');const m=require('../static/product-review-math.js');
const art={kind:'artwork',dimensions:{width_m:.3,height_m:.4},outline:[[100,100],[160,100],[150,300],[100,300]],image_to_plane:[[.005,0,-.5],[0,.004,-.4],[0,.005,.5]]};
const known=art.outline.map(p=>m.plane(art.image_to_plane,p));
const result=m.measure(art,art.outline);assert.equal(result.corner_rms_px,0);assert.ok(Number.isFinite(result.ratio));
assert.throws(()=>m.measure(art,[[0,0],[1,1],[0,1],[1,0]]));
assert.throws(()=>m.measure(art,[[0,0],[0,0],[0,0],[0,0]]));
const pendant={kind:'pendant',dimensions:{diameter_m:.36},image_to_plane:[[.01,0,0],[0,.01,0],[0,0,1]]};
assert.ok(Math.abs(m.measure(pendant,[[0,0],[36,0]]).diameter_m-.36)<1e-10);
const bounds=m.uncertainty(pendant,[[0,0],[36,0]],2);assert.ok(bounds.low<.36&&bounds.high>.36);
assert.throws(()=>m.plane([[1,0,0],[0,1,0],[0,0,0]],[0,0]));
assert.equal(m.alignment([]).rms_px,null);
assert.equal(m.alignment([{expected:[0,0],observed:[3,4]}]).rms_px,5);
assert.equal(m.alignment([{expected:[0,0],observed:[0,0]},{expected:[100,100],observed:[100,100]},{expected:[200,200],observed:[200,200]}]).spatially_distributed,false);
assert.equal(m.alignment([{expected:[0,0],observed:[0,0]},{expected:[1000,0],observed:[1000,0]},{expected:[0,800],observed:[0,800]}]).spatially_distributed,true);
console.log('Product review perspective, selection, uncertainty and alignment checks passed.');
const reviewData={asset_id:'saved-image',image_sha256:'saved-hash',scene_fingerprint:'scene-hash',review_key:'review-hash',camera:{position:[1,2,3]},objects:[{...pendant,id:'pendant',assumptions:['Rim height assumed','Shade height unknown','Suspension length unknown']}],limitations:['Saved camera may differ from generated image']};
const serialized=JSON.stringify(m.buildReport(reviewData,{marks:{pendant:[[0,0],[36,0]]},pairs:[{id:'A',expected:[10,20],observed:[13,24]}],tolerance:2,notes:'Excluded obscured corner'}));
const exported=JSON.parse(serialized);
assert.equal(exported.image,'saved-image');assert.equal(exported.image_sha256,'saved-hash');
assert.equal(exported.approved,false);assert.equal(exported.alignment_status,'UNVERIFIED');assert.equal(exported.metric_status,'INCONCLUSIVE');
assert.equal(exported.alignment.residuals_px[0],5);assert.deepEqual(exported.alignment.span_px,[0,0]);
assert.equal(exported.objects[0].assumptions.length,3);assert.equal(exported.measurements.pendant.result.diameter_m,.36);
assert.ok(exported.measurements.pendant.click_sensitivity.low<.36);
assert.match(exported.uncertainty_method,/not confidence intervals/);
assert.match(exported.architectural_notes,/Excluded/);
console.log('Readable JSON export includes image identity, assumptions, residuals, measurements and uncertainty limits.');
