'use strict';
// Optional contextual tools inside the existing draft editor. All edits use its
// commit/history/save path; this module never accesses or applies the active scene.
(()=>{
const D=SurfaceDesignGeometry,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=> 'design'+crypto.randomUUID().replaceAll('-','');
const labels={painting:'Painting',mirror:'Mirror',sconce:'Wall light',switchboard:'Switchboard',socket:'Socket',tv:'TV panel',shelf:'Shelf',panel:'Decorative panel',pendant:'Pendant',downlight:'Downlight',fan:'Fan',grille:'AC grille',track:'Curtain track',profile:'Profile light',bulkhead:'False ceiling',rug:'Rug',threshold:'Threshold strip',border:'Border strip'};
const palettes={painting:'#b8825b',mirror:'#b5d3dd',sconce:'#d5ad59',switchboard:'#faf9f3',socket:'#eeeae1',tv:'#3d4650',shelf:'#9d724b',panel:'#bca588',pendant:'#d5ad59',downlight:'#f0daa2',fan:'#b2a995',grille:'#9baab0',track:'#414a4e',profile:'#f9df9f',bulkhead:'#dddcd0',rug:'#ad957e',threshold:'#aa9b85',border:'#6c747a'};
let roomRows=[],roomId='',inspectorTab='material',faceOverview=false,editMode='move',planId=null;
function readContext(){try{return JSON.parse(localStorage.getItem('pixeloid-ui-staging-surface-context:'+doc().id)||'{}')}catch{return {}}}
function rememberContext(){if(!active)return;try{localStorage.setItem('pixeloid-ui-staging-surface-context:'+doc().id,JSON.stringify({roomId,kind,surfaceId,selected:[...selected],inspectorTab,faceOverview}));const key='pixeloid-ui-staging-selection:'+doc().active_project_id,saved=JSON.parse(localStorage.getItem(key)||'{}');if(roomId)localStorage.setItem(key,JSON.stringify({...saved,planId,roomId,floor:roomRows.find(r=>r.id===roomId)?.floor}));}catch{}}
function wallInRoom(w){const r=roomRows.find(r=>r.id===roomId);if(!r)return true;const b=r.bbox,t=Math.max(2,w.thickness/2),lo=[b[0]*doc().width-t,b[1]*doc().height-t],hi=[(b[0]+b[2])*doc().width+t,(b[1]+b[3])*doc().height+t],a=w.points[0],d=w.points[1].map((v,i)=>v-a[i]);let enter=0,leave=1;for(let i=0;i<2;i++){if(Math.abs(d[i])<1e-9){if(a[i]<lo[i]||a[i]>hi[i])return false;}else{const u=(lo[i]-a[i])/d[i],v=(hi[i]-a[i])/d[i];enter=Math.max(enter,Math.min(u,v));leave=Math.min(leave,Math.max(u,v));if(enter>leave)return false;}}return true;}
function inRoom(s){if(!roomId)return true;if(s.room_id)return s.room_id===roomId;if(s.kind!=='wall')return !data().surfaces.some(x=>x.room_id===roomId&&x.kind===s.kind);const w=doc().features.find(w=>w.id===s.wall_id);return !!w&&wallInRoom(w);}
function roomSurface(k){return data().surfaces.find(s=>s.kind===k&&s.room_id===roomId)||data().surfaces.find(s=>s.kind===k&&!s.room_id&&inRoom(s));}
function focus3d(scene){const r=roomRows.find(r=>r.id===roomId);if(!active||!r)return null;const b=r.bbox,m=mpp(),w=doc().width*m,d=doc().height*m,H=doc().wall_height_m;return {center:[(b[0]+b[2]/2-(scene?.bounds?.[0]||0))*w,(b[1]+b[3]/2-(scene?.bounds?.[1]||0))*d,H/2],radius:Math.hypot(b[2]*w,b[3]*d,H)/2};}
let h,active=false,kind='wall',surfaceId=null,selected=new Set(),box=[0,0,6,4],gesture=null,guides=[],drawing=null,pendingKind=null,previousDoc=null;
const doc=()=>h.doc(),data=()=>doc().surface_design||{version:1,surfaces:[],items:[],hidden_categories:[]},surface=()=>data().surfaces.find(s=>s.id===surfaceId),items=()=>data().items.filter(o=>o.surface_id===surfaceId),selectedItems=()=>items().filter(o=>selected.has(o.id)),mpp=()=>doc()?.calibration?.metres_per_pixel||0;
const unit=()=>doc().units||'m',factor=()=>unit()==='ft'?.3048:unit()==='in'?.0254:1,fmt=v=>`${(v/factor()).toFixed(3)} ${unit()}`,val=v=>((v??0)/factor()).toFixed(3),parse=v=>TraceGeometry.parseLength(String(v).trim().replace(/^\./,'0.'),unit()),signed=v=>String(v).trim().startsWith('-')?-parse(String(v).trim().slice(1)):String(v).trim()==='0'?0:parse(v);
const field=(label,key,value,type='text')=>`<label class="field"><span>${esc(label)}</span><input data-design-field="${key}" type="${type}" value="${esc(value)}"></label>`,select=(label,key,value,options)=>`<label class="field"><span>${esc(label)}</span><select data-design-field="${key}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===String(value)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`,button=(text,action)=>`<button data-design-action="${action}">${text}</button>`;
const placementKey=o=>JSON.stringify(['surface_id','x','y','width','height','depth','rotation','drop','run'].map(k=>o[k]));
function update(fn){h.commit(()=>{const old=new Map((doc().surface_design?.items||[]).map(o=>[o.id,placementKey(o)]));doc().surface_design||={version:1,surfaces:[],items:[],hidden_categories:[]};fn(doc().surface_design);for(const o of doc().surface_design.items){if(old.get(o.id)===placementKey(o))continue;const host=doc().surface_design.surfaces.find(s=>s.id===o.surface_id);if(host){const problems=D.conflicts(doc(),host,o);if(host.kind==='ceiling'&&(o.drop||0)+o.depth>(host.elevation_m||0))problems.push('Fixture drop extends below the floor');if(problems.length)throw Error(problems.join('; '));}}if(JSON.stringify(doc()).length>950000)throw Error('Draft reference previews exceed 950 KB. Use fewer or smaller reference images.');});}
function coords(e){const p=h.svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(h.svg.getScreenCTM().inverse());return [q.x,q.y];}
function display(s,p){const c=D.context(doc(),s);return s.kind==='wall'?[s.side===1?c.L-p[0]:p[0],-p[1]]:p.map((v,i)=>v+c.origin[i]);}
function local(s,p){const c=D.context(doc(),s);return s.kind==='wall'?[s.side===1?c.L-p[0]:p[0],-p[1]]:p.map((v,i)=>v-c.origin[i]);}
function bounds(){const r=roomRows.find(r=>r.id===roomId);if(!faceOverview&&kind!=='wall'&&r)return [r.bbox[0]*doc().width*mpp(),r.bbox[1]*doc().height*mpp(),r.bbox[2]*doc().width*mpp(),r.bbox[3]*doc().height*mpp()];const s=surface();if(kind==='wall'&&s&&!faceOverview){const c=D.context(doc(),s);if(!c.missing)return [0,-c.H,c.L,c.H];}const ps=doc().features.flatMap(f=>f.points).map(p=>p.map(v=>v*mpp()));if(!ps.length)return [0,0,6,4];const xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]);return [Math.min(...xs),Math.min(...ys),Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys)];}
function fit(){const b=bounds(),r=h.svg.clientWidth/Math.max(1,h.svg.clientHeight),w=Math.max(b[2],b[3]*r,.5)*1.25;box=[b[0]+b[2]/2-w/2,b[1]+b[3]/2-w/r/2,w,w/r];draw();}
async function open(){if(!doc()||!mpp()){h.toast('Open a calibrated draft first.');return;}try{const state=await fetch('/api/state').then(r=>r.json()),project=state.projects?.[doc().active_project_id]||Object.values(state.projects||{}).find(p=>p.manual_draft_id===doc().id);const plan=Object.values(state.assets||{}).find(a=>a.manual_draft_id===doc().id||a.manual_document?.id===doc().id||a.drawing?.manual_draft_id===doc().id);planId=plan?.id;roomRows=(project?.rooms||[]).filter(r=>r.bbox&&(!plan||r.plan_id===plan.id));let saved={};try{saved=JSON.parse(localStorage.getItem('pixeloid-ui-staging-selection:'+doc().active_project_id)||'{}')}catch{}const target=new URLSearchParams(location.search).get('room')||saved.roomId||readContext().roomId;roomId=roomRows.some(r=>r.id===target)?target:roomRows[0]?.id||'';}catch{roomRows=[];}const w=h.wall();active=true;document.body.classList.add('surface-editing');surfaceTools();previousDoc=doc().id;selected.clear();const saved=readContext();kind=saved.kind||'wall';surfaceId=data().surfaces.find(s=>w&&s.wall_id===w.id&&inRoom(s))?.id||data().surfaces.find(s=>s.id===saved.surfaceId&&inRoom(s))?.id||roomSurface(kind)?.id||null;kind=surface()?.kind||kind;inspectorTab=saved.inspectorTab||'material';selected=new Set((saved.selected||[]).filter(id=>items().some(o=>o.id===id)));faceOverview=kind==='wall'&&(!surfaceId||saved.faceOverview===true);h.clearSelection();h.mode('2d');fit();h.render();}
function close(){rememberContext();for(const b of document.querySelectorAll?.('#stages [data-stage]')||[])b.dataset.stage==='plan'?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current');active=false;document.body.classList.remove('surface-editing');document.querySelector('#surface-tools')?.remove();document.querySelector('#viewe').disabled=false;gesture=null;drawing=null;pendingKind=null;guides=[];selected.clear();h.mode('2d');h.render();h.fit();}
function chooseMode(k){kind=k;faceOverview=k==='wall';surfaceId=roomSurface(k)?.id||null;selected.clear();drawing=null;h.mode('2d');fit();h.render();}
function changeSurface(id){surfaceId=id;faceOverview=false;kind=surface()?.kind||kind;if(surface()?.room_id)roomId=surface().room_id;selected.clear();h.mode('2d');fit();h.render();}
function addWall(){const wallId=document.querySelector('#design-wall').value,side=Number(document.querySelector('#design-side').value);const found=data().surfaces.find(s=>s.wall_id===wallId&&s.side===side);if(found){changeSurface(found.id);return;}const s={id:uid(),kind:'wall',wall_id:wallId,side,label:document.querySelector('#design-face-label').value||`Wall ${doc().features.filter(f=>f.kind==='wall').findIndex(f=>f.id===wallId)+1} · ${side===1?'left':'right'} face`,dimension_status:'assumed'};surfaceId=s.id;update(d=>d.surfaces.push(s));fit();}
function makeItem(k,p){const size=D.kinds[k],s=surface();if(!s)throw Error('Choose or define a surface first.');const c=D.context(doc(),s);if(c.missing)throw Error('Reattach the missing host first.');return {id:uid(),surface_id:s.id,kind:k,x:p?.[0]??c.L/2,y:p?.[1]??c.H/2,width:size[0],height:size[1],depth:size[2],rotation:0,drop:k==='pendant'?.4:0,placeholder:true,reference:{dimension_status:'assumed',aspect_locked:true,crop:false}};}
function addItem(k,p){const o=makeItem(k,p);selected=new Set([o.id]);inspectorTab='items';update(d=>d.items.push(o));}
function material(){return {kind:'tile',color:'#d9d0c1',tile_width:.6,tile_length:.6,rotation:0,offset_x:0,offset_y:0,grout:.003,grout_color:'#8d8981',layout:'grid',bookmatch:false,reference:{dimension_status:'assumed'}};}
function finishTarget(){return inspectorTab==='items'&&selectedItems().length===1?selectedItems()[0]:surface();}
function inspector(){if(!active)return false;rememberContext();surfaceTools();if(previousDoc!==doc()?.id){active=false;return false;}const s=faceOverview?null:surface(),c=s?D.context(doc(),s):null,os=faceOverview?[]:selectedItems(),o=os.length===1?os[0]:null,u=unit(),available=kind==='wall'?['painting','mirror','sconce','switchboard','socket','tv','shelf','panel']:kind==='ceiling'?['pendant','downlight','fan','grille','track','profile','bulkhead']:['rug','threshold','border'];
let html=`<h2>Design surfaces</h2><div class="actions">${button('Return to floor plan','close')}</div><div class="actions">${button('Walls','wall')}${button('Ceiling','ceiling')}${button('Floors','floor')}</div><p class="help">${kind==='wall'?'Select a wall face. Local X is measured from end A; heights from floor.':kind==='ceiling'?'Reflected ceiling plan · same X/Y orientation as the floor plan; no mirroring. Explicit boundaries only.':'Floor finishes · explicit boundaries and voids. Physical pattern scale.'}</p>`;
html+=select('Surface','surface',surfaceId||'',[['','Choose…'],...data().surfaces.filter(s=>s.kind===kind&&inRoom(s)).map(s=>[s.id,s.label])]);
if(kind==='wall')html+=`<details ${!s?'open':''}><summary>Choose / add a wall face</summary><label class="field">Wall<select id="design-wall">${doc().features.filter(w=>w.kind==='wall').map((w,i)=>`<option value="${esc(w.id)}">Wall ${i+1} · ${esc(w.id)}</option>`).join('')}</select></label><label class="field">Side of A → B<select id="design-side"><option value="-1">Right face · looking A → B</option><option value="1">Left face · looking B → A</option></select></label><label class="field">Room / face name<input id="design-face-label" placeholder="e.g. Living room · sofa wall"></label>${button('Use this face','add-wall')}</details>`;
else html+=`<div class="actions">${roomRows.length?button('Use selected room boundary','room-boundary'):''}${button('Draw boundary','boundary')}${s?button('Draw void','hole'):''}</div><p class="help">Click vertices, then Enter. Escape cancels. Draw voids for courts/shafts; no automatic ceiling or room inference.</p>`;
if(drawing)html+='<p class="notice">Drawing '+esc(drawing.type)+' · '+drawing.points.length+' points · Enter finishes.</p>';
if(s){html+=field('Surface / room label','surface-label',s.label);if(c.missing)html+='<p class="notice">Host wall missing. All items are retained. Choose a wall above, then '+button('Reattach this face','reattach')+'</p>';if(kind!=='wall')html+=field((kind==='ceiling'?'Ceiling elevation':'Floor elevation')+' · '+u+' (assumed unless checked)','elevation',val(s.elevation_m||0))+`<details><summary>Boundary vertices</summary><label class="field">Plan X,Y in metres · semicolon separated<textarea data-design-field="boundary">${s.boundary.map(p=>p.map(v=>(v*mpp()).toFixed(4)).join(',')).join('; ')}</textarea></label><p class="help">Explicit boundary; source walls stay unchanged. Invalid/crossing polygons are rejected when saved.</p></details>`;

if(os.length){html+=`<h3>${os.length===1?esc(labels[o.kind]):os.length+' items selected'}</h3><div class="actions">${button('Duplicate','duplicate')}${button('Delete','delete')}</div><div class="actions">${['left','right','top','bottom','centre-x','centre-y','space'].map(a=>button(a.replace('centre-x','Centre X').replace('centre-y','Centre Y').replace('space','Equal spacing'),'align:'+a)).join('')}</div>`;}
if(o){const issues=D.conflicts(doc(),s,o);html+=`<p class="notice">Placeholder geometry · ${esc(o.reference?.dimension_status||'assumed')} dimensions. Not an exact product model.</p>${issues.map(t=>'<p class="notice">'+esc(t)+'</p>').join('')}<div class="pair">${field('Width · '+u,'width',val(o.width))}${field((kind==='wall'?'Height':'Plan length')+' · '+u,'height',val(o.height))}${field('Depth · '+u,'depth',val(o.depth))}${field('Rotation · °','rotation',o.rotation,'number')}${field((kind==='wall'?'Centre from A':'Local centre X')+' · '+u,'x',val(o.x))}${field((kind==='wall'?'Mounting centre height':'Local centre Y')+' · '+u,'y',val(o.y))}</div>`;
if(kind==='ceiling')html+=field('Suspension / drop · '+u+' (assumed)','drop',val(o.drop||0));
html+=field('Product URL','product_url',o.reference?.product_url||'')+`<div class="actions">${button('Read product link','product')}${button('Reference image','reference')}</div>`+select('Dimension evidence','dimension_status',o.reference?.dimension_status||'assumed',[['assumed','Assumed'],['extracted','Extracted · needs review'],['verified','Verified by you']])+`<label><input data-design-field="aspect_locked" type="checkbox" ${o.reference?.aspect_locked!==false?'checked':''}> Preserve reference aspect ratio</label><label><input data-design-field="crop" type="checkbox" ${o.reference?.crop?'checked':''}> Explicit crop to item rectangle</label>`;
if(o.reference?.image)html+=`<img class="design-reference" src="${esc(o.reference.image)}" alt="Saved product reference">`;
if(o.reference?.dimensions)html+='<p class="help">Published dimensions (not applied): '+esc(o.reference.dimensions)+'</p>';
if(['sconce','pendant','downlight','profile'].includes(o.kind))html+=`<details><summary>Light settings · separate from geometry</summary>${field('Lumens · no lighting simulation','lumens',o.light?.lumens||0,'number')}${field('Colour temperature · K','kelvin',o.light?.kelvin||3000,'number')}</details>`;
if(['profile','track'].includes(o.kind))html+=`<label class="field">Local run vertices in metres · x,y; x,y<textarea data-design-field="run">${esc((o.run||[[-o.width/2,0],[o.width/2,0]]).map(p=>p.join(',')).join('; '))}</textarea></label><p class="help">Polyline vertices relative to item centre. Width controls the default straight run; thickness = plan length.</p>`;
if(kind==='ceiling')html+=field('Row count · 2–20','row-count',3,'number')+field('Row spacing · '+u,'row-spacing',val(.7))+button('Duplicate row along X','row');
}
html+=`<details><summary>Add another item</summary><label class="field">Type<select id="design-type">${available.map(k=>`<option value="${k}">${labels[k]}</option>`).join('')}</select></label><div class="actions">${button('Place on surface','place')}${button('Add at centre','add')}</div><p class="help">${pendingKind?'Click the surface to place '+labels[pendingKind]+'.':'Drag items; Shift-click to select several. Alt disables snapping. Resize: opposite local corner stays fixed. Group drag snaps the grabbed item; the group moves rigidly.'}</p></details>`;
const target=faceOverview?null:finishTarget(),f=target?.finish?{...material(),...target.finish}:null;html+=`<details ${f?'open':''}><summary>${o?'Item / accent':'Selected face'} finish</summary>${f?select('Material','finish.kind',f.kind,['paint','wallpaper','wood','stone','tile','marble'].map(v=>[v,v]))+field('Colour','finish.color',f.color,'color')+`<div class="pair">${field('Tile / texture width · '+u,'finish.tile_width',val(f.tile_width))}${field('Tile / texture length · '+u,'finish.tile_length',val(f.tile_length))}${field('Rotation · °','finish.rotation',f.rotation,'number')}${field('Start X · '+u,'finish.offset_x',val(f.offset_x))}${field('Start Y · '+u,'finish.offset_y',val(f.offset_y))}${field('Grout width · '+u,'finish.grout',val(f.grout))}</div>`+field('Grout colour','finish.grout_color',f.grout_color,'color')+select('Layout','finish.layout',f.layout,[['grid','Straight grid'],['staggered','Staggered']])+`<label><input type="checkbox" data-design-field="finish.bookmatch" ${f.bookmatch?'checked':''}> Alternate mirrored / bookmatched columns</label>`+field('Material product URL','finish.reference.product_url',f.reference?.product_url||'')+button('Read material link','finish-product')+select('Material dimension evidence','finish.reference.dimension_status',f.reference?.dimension_status||'assumed',[['assumed','Assumed'],['extracted','Extracted · needs review'],['verified','Verified by you']])+button('Texture reference','texture')+button('Remove finish','remove-finish'):button('Add finish','finish')}<p class="help">Applied only to this surface. 3D uses sampled reference colours; grain is a design approximation, not a supply guarantee.</p></details>`;
}
html+=`<details><summary>Visibility</summary>${['wall','floor','ceiling',...Object.keys(labels)].map(k=>`<label><input type="checkbox" data-design-hide="${k}" ${data().hidden_categories?.includes(k)?'':'checked'}> ${labels[k]||k}</label>`).join('')}<label><input type="checkbox" data-design-field="show_ceiling" ${data().show_ceiling?'checked':''}> Show ceiling surface in 3D (otherwise cutaway)</label></details><div class="actions">${button('View in 3D','3d')}${button('Return to structure','close')}</div><p class="help">${doc().active_project_id?'Active apartment · saving updates the shared scene.':'Draft · current apartment unchanged.'} Default dimensions are assumptions.</p>`;
document.querySelector('#inspector').innerHTML=html;
const pane=document.querySelector('#inspector');
const tabs=document.createElement('div');tabs.className='surface-tabs actions';tabs.setAttribute('role','group');tabs.setAttribute('aria-label','Surface inspector');tabs.innerHTML=['material','items'].map(t=>`<button data-design-action="tab:${t}" aria-pressed="${inspectorTab===t}">${t==='material'?'Material':'Items'}</button>`).join('');
const roomField=document.createElement('label');roomField.className='field';roomField.innerHTML='Room<select data-design-field="room">'+(roomRows.length?roomRows.map(r=>`<option value="${r.id}" ${r.id===roomId?'selected':''}>${esc(r.name)}</option>`).join(''):'<option value="">Draft · explicit surfaces</option>')+'</select>';
pane.querySelector('h2').after(roomField);const surfaceField=pane.querySelector('[data-design-field="surface"]').closest('label');surfaceField.after(tabs);
for(const b of pane.querySelectorAll('[data-design-action="close"]'))b.parentElement.remove();
const back=document.createElement('button');back.dataset.designAction='faces';back.textContent='Choose face on plan';surfaceField.after(back);back.hidden=kind!=='wall';
const advanced=document.createElement('details');advanced.className='surface-advanced';advanced.innerHTML='<summary>Advanced · boundary & evidence</summary>';pane.append(advanced);
for(const key of ['surface-label','elevation','boundary']){const el=pane.querySelector(`[data-design-field="${key}"]`);if(el)advanced.append(el.closest('details')||el.closest('label'));}
const addWall=pane.querySelector('[data-design-action="add-wall"]')?.closest('details');if(addWall)advanced.append(addWall);
const boundary=pane.querySelector('[data-design-action="boundary"]')?.parentElement;if(boundary){const roomButton=boundary.querySelector('[data-design-action="room-boundary"]');if(roomButton)surfaceField.after(roomButton);advanced.append(boundary);}
const finish=pane.querySelector('[data-design-action="finish"],[data-design-action="remove-finish"]')?.closest('details');if(finish){finish.open=true;finish.classList.add('surface-material');finish.hidden=inspectorTab!=='material';tabs.after(finish);const thumb=finishTarget()?.finish?.reference?.image;finish.insertAdjacentHTML('afterbegin',thumb?`<img class="design-reference" src="${esc(thumb)}" alt="Material reference">`:'<span class="reference-empty">No texture</span>');}
const catalogue=pane.querySelector('[data-design-action="add"]')?.closest('details');if(catalogue){catalogue.open=true;catalogue.hidden=inspectorTab!=='items';catalogue.classList.add('surface-item-catalogue');tabs.after(catalogue);}
for(const el of Array.from(pane.children)){if(el===advanced||el===tabs||el===roomField||el===surfaceField||el===finish||el===catalogue||el===back||el.tagName==='H2'||el.classList.contains('surface-tabs'))continue;if(el.matches('.pair,h3,.notice')||el.querySelector('[data-design-action="duplicate"],[data-design-action^="align:"]')||el.querySelector('[data-design-field="drop"],[data-design-field="product_url"],[data-design-field="dimension_status"],[data-design-field="aspect_locked"],[data-design-field="crop"],[data-design-action="reference"]')||el.classList.contains('design-reference'))el.hidden=inspectorTab!=='items';}
if(pane.querySelectorAll){const extras=document.createElement('details');extras.innerHTML='<summary>Surface help</summary>';for(const p of pane.querySelectorAll(':scope > p.help'))extras.append(p);pane.append(extras);
const align=null;if(align){const details=document.createElement('details');details.innerHTML='<summary>Align selected items</summary>';align.before(details);details.append(align);}
const shape=pane.querySelector('[data-design-field="width"]')?.closest('.pair'),head=pane.querySelector('h3');if(shape&&head)head.after(shape);
const product=null;if(product){const details=document.createElement('details');details.innerHTML='<summary>Product link & aspect options</summary>';product.before(details);details.append(product);const lookup=pane.querySelector('[data-design-action="product"]');if(lookup)details.append(lookup);for(const key of ['aspect_locked','crop']){const label=pane.querySelector('[data-design-field="'+key+'"]')?.closest('label');if(label)details.append(label);}}
const image=pane.querySelector('.design-reference');if(image&&shape)shape.after(image);
}
for(const key of ['finish.offset_x','finish.offset_y','finish.grout','finish.grout_color','finish.bookmatch','finish.reference.product_url','finish.reference.dimension_status']){const el=pane.querySelector(`[data-design-field="${key}"]`);if(el)advanced.append(el.closest('label'));}const lookup=pane.querySelector('[data-design-action="finish-product"]');if(lookup)advanced.append(lookup);const tex=pane.querySelector('[data-design-action="texture"]');if(tex&&finish)finish.prepend(tex);const visibility=Array.from(pane.children).find(e=>e.tagName==='DETAILS'&&e.querySelector('summary')?.textContent==='Visibility');if(visibility)advanced.append(visibility);if(finish)for(const p of finish.querySelectorAll('p.help'))advanced.append(p);
for(const key of ['row-count','row-spacing']){const el=pane.querySelector(`[data-design-field="${key}"]`);if(el)advanced.append(el.closest('label'));}const rowAction=pane.querySelector('[data-design-action="row"]');if(rowAction)advanced.append(rowAction);
if(o&&inspectorTab==='items'){if(catalogue)catalogue.open=false;
 const shape=pane.querySelector('[data-design-field="width"]')?.closest('.pair'),head=pane.querySelector('h3');if(head&&shape){tabs.after(head);head.after(shape);}
 const drop=pane.querySelector('[data-design-field="drop"]')?.closest('label');if(drop&&shape)shape.append(drop);
 const ref=pane.querySelector('[data-design-action="reference"]');if(ref&&shape){const row=document.createElement('div');row.className='surface-reference actions';head.after(row);const img=pane.querySelector('.design-reference');if(img)row.append(img);else{const empty=document.createElement('span');empty.className='reference-empty';empty.textContent='No reference';row.append(empty);}row.append(ref);if(catalogue)shape.after(catalogue);}
 for(const key of ['row-count','row-spacing','aspect_locked','crop']){const el=pane.querySelector(`[data-design-field="${key}"]`);if(el)advanced.append(el.closest('label'));}
 const row=pane.querySelector('[data-design-action="row"]');if(row)advanced.append(row);
 const align=pane.querySelector('[data-design-action^="align:"]')?.parentElement;if(align){const details=document.createElement('details');details.innerHTML='<summary>Align / distribute</summary>';align.before(details);details.append(align);}
}
for(const key of ['product_url','dimension_status']){const el=pane.querySelector(`[data-design-field="${key}"]`);if(el)advanced.append(el.closest('label'));}const product=pane.querySelector('[data-design-action="product"]');if(product)advanced.append(product);
if(catalogue)for(const help of catalogue.querySelectorAll('p.help'))advanced.append(help);const roomBoundary=pane.querySelector('[data-design-action="room-boundary"]');if(roomBoundary&&s?.room_id===roomId)roomBoundary.hidden=true;
for(const b of document.querySelectorAll?.('#stages [data-stage]')||[])b.dataset.stage==='surfaces'?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current');return true;}
function surfaceTools(){h.svg.setAttribute('aria-label',`Surface design · ${kind} · ${pendingKind?'Click to place '+labels[pendingKind]:drawing?'Click boundary vertices; Enter to finish':faceOverview?'Choose a wall face':editMode==='rotate'?'Drag an item to rotate; Alt disables angle snapping':'Select or drag surface items; Shift-click for multiple selection'}`);h.svg.style.cursor=pendingKind||drawing?'crosshair':'default';const elevation=document.querySelector('#viewe');if(elevation){elevation.disabled=kind!=='wall';elevation.title=kind==='wall'?'Wall surface elevation':'Choose a wall face for elevation';}if(!h.is3d()&&kind==='wall'&&!faceOverview){document.querySelector('#viewe')?.setAttribute('aria-pressed','true');document.querySelector('#view2')?.setAttribute('aria-pressed','false');}let nav=document.querySelector('#surface-tools');if(!nav){nav=document.createElement('nav');nav.id='surface-tools';nav.setAttribute('aria-label','Surface tools');document.querySelector('.tools').after(nav);}nav.innerHTML=button('Select','select')+button('Material','material')+button('Add item','items')+button('Move','move')+button('Rotate','rotate')+button('Solid','solid')+button('X-ray','xray')+button('Edges','edges')+button('Cutaway','cutaway');nav.querySelector(`[data-design-action="${editMode}"]`)?.setAttribute('aria-pressed','true');let appearance=h.viewer?.()?.view||{};for(const [a,k] of [['solid','transparent'],['xray','transparent'],['edges','edges'],['cutaway','cutaway']])nav.querySelector(`[data-design-action="${a}"]`)?.setAttribute('aria-pressed',String(a==='solid'?!appearance[k]:!!appearance[k]));}
function drawFacePlan(){
 const m=mpp(),px=box[2]/Math.max(1,h.svg.clientWidth);h.svg.setAttribute('viewBox',box.join(' '));let html='',names='';
 for(const r of roomRows){const points=D.roomPolygon(doc(),r).map(p=>p.map(v=>v*m)),b=r.bbox,chosen=r.id===roomId;
  html+=`<path data-design-room="${esc(r.id)}" d="${polygon(points)}" fill="${chosen?'#5482a9':'#91a3af'}" fill-opacity="${chosen?'.22':'.05'}" stroke="#7894a8" stroke-width="${px}" stroke-dasharray="${3*px}" pointer-events="none"/>`;
  names+=`<text class="surface-caption" x="${(b[0]+b[2]/2)*doc().width*m}" y="${(b[1]+b[3]/2)*doc().height*m}" text-anchor="middle" font-size="${12*px}" font-weight="${chosen?700:400}" pointer-events="none">${esc(r.name)}${chosen?' · selected':''}</text>`;
 }
 for(const w of doc().features.filter(f=>f.kind==='wall')){const relevant=wallInRoom(w),attr=relevant?`data-design-wall="${w.id}" tabindex="0" role="button" aria-label="Choose wall face ${esc(w.id)}"`:'';
  html+=`<path ${attr} d="M${w.points.map(p=>p.map(v=>v*m).join(',')).join(' L')}" fill="none" stroke="${relevant?'#5482a9':'#b5bdc3'}" stroke-width="${Math.max(w.thickness*m,8*px)}"/>`;
  const c=D.context(doc(),{kind:'wall',wall_id:w.id,side:1});
  for(const o of doc().features.filter(o=>o.host_wall_id===w.id&&['door','window'].includes(o.kind))){const points=[o.offset,o.offset+o.width].map(x=>c.origin.map((v,i)=>v+c.u[i]*x*m));html+=`<path ${relevant?`data-design-wall="${w.id}"`:""} d="M${points.join(' L')}" stroke="${o.kind==='door'?'#d6ad71':'#7ac6d3'}" stroke-width="${Math.max(w.thickness*m*.75,5*px)}"><title>${esc(o.kind)}</title></path>`;}
 }
 h.svg.innerHTML=html+names;document.querySelector('#floating').textContent='Choose a wall · highlighted room · door and window openings shown';
}
function partitionContext(s,c,px){
 let out='<g data-partition-context="true" pointer-events="none">';
 for(const p of D.wallPartitions(doc(),s)){const x=display(s,[p.x,0])[0],width=Math.max(p.width,2*px);
  out+=`<g data-partition="${esc(p.id)}"><title>Partition at ${esc(fmt(p.x))} from A${p.facing?'':' · opposite face'}</title><rect x="${x-width/2}" y="${-p.height}" width="${width}" height="${p.height}" fill="${p.facing?'#8195a2':'none'}" fill-opacity=".65" stroke="#4d6577" stroke-width="${px}" ${p.facing?'':`stroke-dasharray="${4*px}"`}/><text class="surface-caption" x="${x}" y="${-c.H-34*px}" font-size="${10*px}" text-anchor="middle">Partition${p.facing?'':' · opposite'}</text></g>`;
 }
 for(const r of roomRows){for(const [a,b] of D.roomWallSpans(doc(),s,r)){const x1=display(s,[a,0])[0],x2=display(s,[b,0])[0],chosen=r.id===roomId;
  out+=`<path data-room-span="${esc(r.id)}" d="M${x1},${32*px} v${6*px} H${x2} v${-6*px}" fill="none" stroke="${chosen?'#5482a9':'#8195a2'}" stroke-width="${(chosen?2:1)*px}"/><text class="surface-caption" x="${(x1+x2)/2}" y="${54*px}" text-anchor="middle" font-size="${11*px}" font-weight="${chosen?700:400}">${esc(r.name)}${chosen?' · selected':''}</text>`;
 }}return out+'</g>';
}
function begin3d(hit,p){if(!active)return null;const o=selectedItems()[0],s=surface(),viewer=h.viewer();if(!o)return null;const c=D.context(doc(),s),faces=viewer.faces.filter(f=>f.id===o.id),points=faces.flatMap(f=>f.points),centre=[0,1,2].map(i=>points.reduce((n,p)=>n+p[i],0)/points.length),handle=BlockModelViewer.project(centre,viewer.view,viewer.bounds,viewer.canvas.clientWidth,viewer.canvas.clientHeight);if(hit?.id!==o.id&&Math.hypot(p[0]-handle[0],p[1]-handle[1])>24)return null;const normal=s.kind==='wall'?[...c.n,0]:[0,0,1],ray=BlockModelViewer.rayFor(p,viewer.view,viewer.bounds,viewer.canvas.clientWidth,viewer.canvas.clientHeight),point=BlockModelViewer.planePoint(ray,centre,normal);if(!point)return null;return {o:D.copy(o),s,c,centre,normal,point,faces:faces.map(f=>({...f,points:D.copy(f.points)})),mode:editMode,preview:D.copy(o)};}
function move3d(g,ray,delta,event){const p=BlockModelViewer.planePoint(ray,g.centre,g.normal);if(!p)return;let o=D.copy(g.o);if(g.mode==='rotate')o.rotation=g.o.rotation+delta[0]*(event.altKey?.3:1);else{const v=p.map((n,i)=>n-g.point[i]);o.x+=g.s.kind==='wall'?v[0]*g.c.u[0]+v[1]*g.c.u[1]:v[0];o.y+=g.s.kind==='wall'?v[2]:v[1];if(!event.altKey&&document.querySelector('#snap').checked)o=D.snap(doc(),g.s,o,.06).item;}
 const errors=D.conflicts(doc(),g.s,o);if(errors.length){h.toast(errors[0]);return;}g.preview=o;const before=D.world(doc(),g.s,g.o),after=D.world(doc(),g.s,o),shift=after.map((v,i)=>v-before[i]),angle=(o.rotation-g.o.rotation)*Math.PI/180,n=g.normal,cos=Math.cos(angle),sin=Math.sin(angle),viewer=h.viewer();for(const original of g.faces){const f=viewer.faces.find(f=>f===original)||viewer.faces.find(f=>f.id===original.id&&f.points.length===original.points.length&&JSON.stringify(f._editOriginal||f.points)===JSON.stringify(original.points));if(!f)continue;f._editOriginal=original.points;f.points=original.points.map(p=>{const v=p.map((x,i)=>x-g.centre[i]),dot=v.reduce((x,q,i)=>x+q*n[i],0),cross=[n[1]*v[2]-n[2]*v[1],n[2]*v[0]-n[0]*v[2],n[0]*v[1]-n[1]*v[0]];return v.map((q,i)=>g.centre[i]+q*cos+cross[i]*sin+n[i]*dot*(1-cos)+shift[i]);});}viewer.draw();document.querySelector('#floating').textContent=`${labels[o.kind]} · ${fmt(o.width)} × ${fmt(o.height)} · X ${fmt(o.x)} · Y ${fmt(o.y)} · ${Math.round(o.rotation)}°`;
}
function end3d(g,cancel){const viewer=h.viewer();for(const f of viewer.faces)if(f._editOriginal){f.points=f._editOriginal;delete f._editOriginal;}if(!cancel)update(d=>{d.items=d.items.map(o=>o.id===g.o.id?g.preview:o);});else viewer.draw();}
function gizmo3d(viewer){let el=document.querySelector('#surface-gizmo');if(!el){el=document.createElement('span');el.id='surface-gizmo';viewer.canvas.after(el);}const o=selectedItems()[0],ps=viewer.faces.filter(f=>f.id===o?.id).flatMap(f=>f.points);el.hidden=!active||!h.is3d()||!ps.length;if(el.hidden)return;const centre=[0,1,2].map(i=>ps.reduce((n,p)=>n+p[i],0)/ps.length),p=BlockModelViewer.project(centre,viewer.view,viewer.bounds,viewer.canvas.clientWidth,viewer.canvas.clientHeight);el.style.left=viewer.canvas.offsetLeft+p[0]+'px';el.style.top=viewer.canvas.offsetTop+p[1]+'px';el.textContent=editMode==='rotate'?'↻':'✥';}

function pattern(f,id,px,s){const w=f.tile_width||.6,l=f.tile_length||.6,g=f.grout||0,image=f.reference?.image;const cell=(x,y,mirror=false)=>`<rect x="${x}" y="${y}" width="${w-g}" height="${l-g}" fill="${f.color}"/>${image?`<image href="${esc(image)}" x="${mirror?-x-w+g:x}" y="${y}" width="${w-g}" height="${l-g}" preserveAspectRatio="xMidYMid slice" ${mirror?'transform="scale(-1 1)"':''}/>`:''}`;return `<pattern id="${id}" patternUnits="userSpaceOnUse" width="${w*(f.bookmatch?2:1)}" height="${l*(f.layout==='staggered'?2:1)}" patternTransform="${s?(s.kind==='wall'?`matrix(${s.side===1?-1:1} 0 0 -1 ${s.side===1?D.context(doc(),s).L:0} 0)`:`translate(${D.context(doc(),s).origin})`):''} translate(${f.offset_x||0} ${f.offset_y||0}) rotate(${f.rotation||0})"><rect width="100%" height="100%" fill="${f.grout_color}"/>${cell(g/2,g/2)}${f.bookmatch?cell(w+g/2,g/2,true):''}${f.layout==='staggered'?cell(-w/2+g/2,l+g/2)+cell(w/2+g/2,l+g/2)+ (f.bookmatch?cell(w*1.5+g/2,l+g/2,true):''):''}</pattern>`;}
function polygon(ps){return 'M'+ps.map(p=>p.join(',')).join(' L')+' Z';}
function draw(){if(!active||!doc())return false;rememberContext();surfaceTools();if(faceOverview){drawFacePlan();return true;}if(previousDoc!==doc().id){active=false;return false;}const s=surface(),c=s?D.context(doc(),s):null,px=box[2]/Math.max(1,h.svg.clientWidth);h.svg.setAttribute('viewBox',box.join(' '));let html='<defs>',body='';const hidden=data().hidden_categories||[];
for(const sf of data().surfaces.filter(sf=>sf.kind===kind)){if(hidden.includes(kind))continue;const ct=D.context(doc(),sf);if(ct.missing)continue;let path;if(kind==='wall'){if(sf.id!==surfaceId)continue;path=polygon([[0,0],[ct.L,0],[ct.L,-ct.H],[0,-ct.H]]);for(const op of D.openingRects(doc(),sf))path+=' '+polygon(D.corners(op).map(p=>display(sf,p)));}else path=polygon(sf.boundary.map(p=>p.map(v=>v*mpp())))+(sf.holes||[]).map(hole=>' '+polygon(hole.map(p=>p.map(v=>v*mpp())))).join('');
const f=sf.finish,pat='pat'+sf.id;html+=`<clipPath id="clip${sf.id}"><path d="${path}" clip-rule="evenodd"/></clipPath>`+(f?pattern(f,pat,px,sf):'');body+=`<path data-design-surface="${sf.id}" d="${path}" fill-rule="evenodd" fill="${f?(f.kind==='paint'?f.color:'url(#'+pat+')'):kind==='wall'?'#ebe7df':kind==='ceiling'?'#eceeea':'#f3eee6'}" stroke="${sf.id===surfaceId?'#578099':'#9aabae'}" stroke-width="${px}"/>`;
if(kind==='wall'){for(const op of D.openingRects(doc(),sf)){body+=`<path d="${polygon(D.corners(op).map(p=>display(sf,p)))}" fill="#d3e1e7" stroke="#6e8592" stroke-width="${px}"/><text x="${display(sf,[op.x,op.y])[0]}" y="${-op.y}" font-size="${11*px}" text-anchor="middle">Opening</text>`;}}
}
if(kind!=='wall'){const resolved=h.footprints?.();if(resolved)body+=`<path d="${resolved.rings.flatMap(r=>[r.outer,...r.holes]).map(r=>polygon(r.map(p=>p.map(v=>v*mpp())))).join(' ')}" fill="#a1aeb2" fill-rule="evenodd" pointer-events="none"/>`;body+=`<text class="surface-caption" x="${box[0]+15*px}" y="${box[1]+55*px}" font-size="${12*px}" fill="#49637b">${kind==='ceiling'?'REFLECTED CEILING · same plan orientation':'FLOOR FINISH PLAN'} · +X → · +Y ↓</text>`;}
if(s&&!c.missing){if(kind==='wall')body+=partitionContext(s,c,px);const os=items().map(o=>gesture?.previews?.find(q=>q.id===o.id)||o);for(const o of os){if(hidden.includes(o.kind))continue;const pts=D.corners(o).map(p=>display(s,p)),chosen=selected.has(o.id),issues=D.conflicts(doc(),s,o),f=o.finish,pat='pat'+o.id;if(f)html+=pattern(f,pat,px,s);body+=`<g data-design-item="${o.id}" tabindex="0" role="button" aria-label="${esc(labels[o.kind])}"><path d="${polygon(pts)}" fill="${o.run?'transparent':f?(f.kind==='paint'?f.color:'url(#'+pat+')'):palettes[o.kind]}" stroke="${issues.length?'#b74632':chosen?'#245dcc':o.run?'none':'#657b82'}" stroke-width="${(chosen?2:1)*px}"/>`;
if(o.reference?.image){const centre=display(s,[o.x,o.y]),angle=s.kind==='wall'?(s.side===1?o.rotation:-o.rotation):o.rotation;body+=`<image href="${esc(o.reference.image)}" x="${centre[0]-o.width/2}" y="${centre[1]-o.height/2}" width="${o.width}" height="${o.height}" preserveAspectRatio="${o.reference.crop?'xMidYMid slice':'xMidYMid meet'}" transform="rotate(${angle} ${centre})" pointer-events="none"/>`;}
if(o.run)body+=`<path d="M${o.run.map(p=>{const a=o.rotation*Math.PI/180;return display(s,[o.x+p[0]*Math.cos(a)-p[1]*Math.sin(a),o.y+p[0]*Math.sin(a)+p[1]*Math.cos(a)]).join(',');}).join(' L')}" stroke="#d1aa4e" stroke-width="${o.height}" fill="none" pointer-events="none"/>`;
const centre=display(s,[o.x,o.y]);body+=`<text pointer-events="none" x="${centre[0]}" y="${centre[1]}" text-anchor="middle" font-size="${10*px}" fill="#233e55">${esc(labels[o.kind])}</text></g>`;
if(chosen&&!o.run){const corner=display(s,D.corners(o)[2]);body+=`<g data-design-resize="${o.id}"><circle cx="${corner[0]}" cy="${corner[1]}" r="${10*px}" fill="transparent"/><rect x="${corner[0]-3*px}" y="${corner[1]-3*px}" width="${6*px}" height="${6*px}" fill="white" stroke="#245dcc" stroke-width="${px}"/></g>`;if(os.filter(x=>selected.has(x.id)).length===1){const xs=D.corners(o).map(p=>p[0]),ys=D.corners(o).map(p=>p[1]);const summary=o.run?`Run ${fmt(o.run.slice(1).reduce((n,p,i)=>n+Math.hypot(p[0]-o.run[i][0],p[1]-o.run[i][1]),0))} · Thickness ${fmt(o.height)} · D ${fmt(o.depth)}`:`W ${fmt(o.width)} · H ${fmt(o.height)} · D ${fmt(o.depth)}`;body+=`<text class="length-label" x="${centre[0]}" y="${Math.min(...pts.map(p=>p[1]))-12*px}" text-anchor="middle" font-size="${11*px}" pointer-events="none">${esc(summary)}</text>`;if(kind==='wall'){for(const [a,b,t] of [[[0,o.y],[Math.min(...xs),o.y],'A '+fmt(Math.min(...xs))],[[Math.max(...xs),o.y],[c.L,o.y],'B '+fmt(c.L-Math.max(...xs))],[[o.x,0],[o.x,Math.min(...ys)],'Floor '+fmt(Math.min(...ys))]]){const A=display(s,a),B=display(s,b);body+=`<path d="M${A} L${B}" stroke="#51769d" stroke-width="${px}" stroke-dasharray="${3*px}"/><text class="length-label" x="${(A[0]+B[0])/2}" y="${(A[1]+B[1])/2-5*px}" text-anchor="middle" font-size="${10*px}">${esc(t)}</text>`;}}const neighbour=os.filter(q=>q.id!==o.id).sort((a,b)=>Math.abs(a.x-o.x)-Math.abs(b.x-o.x))[0];if(neighbour){const gap=Math.hypot(Math.max(0,Math.abs(neighbour.x-o.x)-(o.width+neighbour.width)/2),Math.max(0,Math.abs(neighbour.y-o.y)-(o.height+neighbour.height)/2));body+=`<text class="length-label" x="${centre[0]}" y="${Math.max(...pts.map(p=>p[1]))+16*px}" text-anchor="middle" font-size="${10*px}">Nearby clearance ${esc(fmt(gap))}</text>`;}}}
}
if(kind==='wall')body+=`<text class="surface-caption" x="${s.side===1?c.L:0}" y="${20*px}" font-size="${11*px}" text-anchor="middle">A</text><text class="surface-caption" x="${s.side===1?0:c.L}" y="${20*px}" font-size="${11*px}" text-anchor="middle">B</text><text class="surface-caption" x="${c.L/2}" y="${-c.H-15*px}" font-size="${11*px}" text-anchor="middle">${esc(s.label)} · ${s.side===1?'Left face · B → A':'Right face · A → B'} · ${fmt(c.L)} × ${fmt(c.H)}</text>`;
for(const g of guides){const ends=g.axis===0?[[g.value,0],[g.value,c.H]]:[[0,g.value],[c.L,g.value]];body+=`<path d="M${ends.map(p=>display(s,p)).join(' L')}" fill="none" stroke="#4679b9" stroke-width="${px}" stroke-dasharray="${4*px}"/>`;}
}
if(drawing&&drawing.points.length)body+=`<path d="M${drawing.points.join(' L')}" fill="none" stroke="#245dcc" stroke-width="${2*px}"/>`;
h.svg.innerHTML=html+'</defs>'+body;document.querySelector('#guidance').textContent='Shift-click: select items · Drag: place · Alt: no snap · Swipe: pan · Pinch: zoom';document.querySelector('#floating').textContent='Surface design · '+(kind==='wall'?'wall elevation':kind==='ceiling'?'reflected ceiling plan':'floor finishes')+' · geometry and dimensions are design assumptions';return true;}
function cancel(){gesture=null;guides=[];drawing=null;pendingKind=null;draw();inspector();}
async function readReference(texture=false){const target=texture?finishTarget():selectedItems()[0];if(!target)throw Error('Select an item first.');const reference=await window.Staging.reference();update(()=>{const owner=texture?(target.finish||={}):target;owner.reference={...owner.reference,...reference};});h.toast('Bundled synthetic reference assigned; dimensions unchanged.');}

async function action(a){const s=surface(),o=selectedItems()[0];if(['wall','ceiling','floor'].includes(a))return chooseMode(a);if(a==='close')return close();if(a.startsWith('tab:')){inspectorTab=a.slice(4);inspector();return;}if(a==='faces'){faceOverview=true;h.mode('2d');fit();inspector();return;}if(a==='select'){editMode='move';pendingKind=null;drawing=null;h.mode('2d');fit();return;}if(a==='material'){inspectorTab='material';inspector();return;}if(a==='items'){inspectorTab='items';inspector();return;}if(a==='move'||a==='rotate'){editMode=a;surfaceTools();return;}if(['solid','xray','edges','cutaway'].includes(a)){const v=h.viewer();if(!v){await h.mode('3d');return action(a);}if(a==='solid')v.view.transparent=false;else{const key=a==='xray'?'transparent':a;v.view[key]=!v.view[key];}localStorage.setItem('pixeloid-ui-staging-model-appearance',JSON.stringify({transparent:v.view.transparent,edges:v.view.edges,cutaway:v.view.cutaway}));v.draw();surfaceTools();return;}if(a==='3d'){h.mode('3d');return;}if(a==='add-wall')return addWall();if(a==='reattach'){const id=document.querySelector('#design-wall').value,side=Number(document.querySelector('#design-side').value);update(()=>{s.wall_id=id;s.side=side;});fit();return;}if(a==='boundary'||a==='hole'){if(a==='hole'&&!s)throw Error('Choose a surface first.');drawing={type:a,points:[]};selected.clear();h.mode('2d');draw();inspector();return;}
if(a==='room-boundary'){const r=roomRows.find(r=>r.id===roomId);if(!r)throw Error('Choose a room.');const existing=data().surfaces.find(s=>s.room_id===r.id&&s.kind===kind);if(existing)return changeSurface(existing.id);const b=r.bbox,ps=r.area_polygon||[[b[0],b[1]],[b[0]+b[2],b[1]],[b[0]+b[2],b[1]+b[3]],[b[0],b[1]+b[3]]];const sf={id:uid(),kind,room_id:r.id,boundary:ps.map(p=>[p[0]*doc().width,p[1]*doc().height]),holes:[],label:r.name+' · '+kind+' · review boundary',elevation_m:kind==='ceiling'?doc().wall_height_m:0,dimension_status:'assumed'};surfaceId=sf.id;update(d=>d.surfaces.push(sf));fit();h.toast('Uses the saved room extent. Review boundary and voids in Advanced before applying finishes.');return;}if(a==='place'){pendingKind=document.querySelector('#design-type').value;inspector();return;}if(a==='add')return addItem(document.querySelector('#design-type').value);
if(a==='duplicate'){const copies=selectedItems().map(o=>({...D.copy(o),id:uid(),x:o.x+.15,y:o.y+.15}));selected=new Set(copies.map(o=>o.id));update(d=>d.items.push(...copies));return;}
if(a==='delete'){update(d=>d.items=d.items.filter(o=>!selected.has(o.id)));selected.clear();h.render();return;}
if(a.startsWith('align:')){let alignment=a.slice(6);if(s.kind==='wall'&&s.side===1)alignment=({left:'right',right:'left'})[alignment]||alignment;if(s.kind!=='wall')alignment=({top:'bottom',bottom:'top'})[alignment]||alignment;const aligned=D.align(selectedItems(),alignment);update(d=>d.items=d.items.map(o=>aligned.find(q=>q.id===o.id)||o));return;}
if(a==='finish'){const target=faceOverview?null:finishTarget();if(!target)throw Error('Choose a face first.');update(()=>target.finish=material());return;}if(a==='remove-finish'){const target=finishTarget();update(()=>delete target.finish);return;}if(a==='reference'||a==='texture')return readReference(a==='texture');
if(a==='row'){const count=Number(document.querySelector('[data-design-field="row-count"]').value),spacing=parse(document.querySelector('[data-design-field="row-spacing"]').value);if(!Number.isInteger(count)||count<2||count>20)throw Error('Use 2–20 fixtures per row.');const copies=Array.from({length:count-1},(_,i)=>({...D.copy(o),id:uid(),x:o.x+(i+1)*spacing}));update(d=>d.items.push(...copies));return;}
if(a==='product'||a==='finish-product'){const target=a==='product'?o:finishTarget().finish;const csrf=await fetch('/api/access/session').then(r=>r.json()),r=await fetch('/api/products/inspect',{method:'POST',headers:{'Content-Type':'application/json','X-Pixeloid-CSRF':csrf.csrf},body:JSON.stringify({url:target.reference?.product_url})}),p=await r.json();if(!r.ok)throw Error(p.error||'Product lookup failed; enter the reference manually.');update(()=>{target.reference={...target.reference,product_id:p.id,title:p.title,dimensions:p.dimensions,dimension_status:'extracted',dimension_notes:p.dimension_notes};});h.toast('Product details saved; dimensions need your review. Upload the selected reference photo to preserve its image in this draft.');}
}
function change(key,input){const s=surface(),o=selectedItems()[0];if(key==='room'){roomId=input.value;surfaceId=roomSurface(kind)?.id||null;selected.clear();faceOverview=kind==='wall';h.mode('2d');fit();inspector();return;}if(key==='surface'){changeSurface(input.value);return;}if(['row-count','row-spacing'].includes(key))return;
update(d=>{if(key==='boundary'){const ps=input.value.split(';').map(t=>t.split(',').map(Number));if(ps.length<3||ps.length>100||ps.some(p=>p.length!==2||p.some(v=>!Number.isFinite(v))))throw Error('Enter at least three valid X,Y metre pairs.');s.boundary=ps.map(p=>p.map(v=>v/mpp()));return;}if(key==='surface-label'){s.label=input.value;return;}if(key==='elevation'){s.elevation_m=signed(input.value);if(s.elevation_m<0||s.elevation_m>20)throw Error('Use an elevation from 0 to 20 m.');return;}if(key==='show_ceiling'){d.show_ceiling=input.checked;return;}if(key.startsWith('finish.')){const f=finishTarget().finish=Object.assign(material(),finishTarget().finish),k=key.slice(7);if(k.startsWith('reference.')){f.reference||={};f.reference[k.slice(10)]=input.value;return;}f[k]=['tile_width','tile_length'].includes(k)?parse(input.value):['offset_x','offset_y','grout'].includes(k)?signed(input.value):k==='rotation'?Number(input.value):k==='bookmatch'?input.checked:input.value;if(f.grout<0||f.grout>=Math.min(f.tile_width,f.tile_length)||!Number.isFinite(f.rotation))throw Error('Grout must be smaller than the tile; rotation must be finite.');return;}if(!o)return;
if(['product_url','dimension_status','aspect_locked','crop'].includes(key)){o.reference||={};o.reference[key]=input.type==='checkbox'?input.checked:input.value;if(key==='aspect_locked'&&input.checked&&o.reference.image_width&&!o.reference.crop)o.width=o.height*o.reference.image_width/o.reference.image_height;return;}
if(key==='lumens'||key==='kelvin'){o.light||={lumens:0,kelvin:3000};const v=Number(input.value);if(!Number.isFinite(v)||v<0||(key==='kelvin'&&(v<1000||v>20000)))throw Error('Enter valid light settings.');o.light[key]=v;return;}
if(key==='run'){const run=input.value.split(';').map(s=>s.split(',').map(Number));if(run.length<2||run.length>50||run.some(p=>p.length!==2||p.some(v=>!Number.isFinite(v)||Math.abs(v)>30)))throw Error('Enter local metre pairs, e.g. -1,0; 0,0; 0,1');o.run=run;return;}
const oldHeight=o.height;const v=key==='rotation'?Number(input.value):['x','y','drop'].includes(key)?signed(input.value):parse(input.value);if(!Number.isFinite(v)||key!=='rotation'&&Math.abs(v)>100||['width','height','depth'].includes(key)&&v<=0||key==='drop'&&v<0)throw Error('Enter a valid dimension.');o[key]=v;
if(['width','height'].includes(key)&&o.reference?.aspect_locked!==false&&!o.reference?.crop&&o.reference?.image_width){const ratio=o.reference.image_width/o.reference.image_height;if(key==='width')o.height=o.width/ratio;else o.width=o.height*ratio;}
if(s.kind==='wall'&&o.height!==oldHeight)o.y+=(o.height-oldHeight)/2; // Bottom stays fixed.
});}
function finishBoundary(){if(!drawing)return;const ps=drawing.points.map(p=>p.map(v=>v/mpp()));if(ps.length<3)throw Error('Use at least three boundary points.');if(drawing.type==='hole'){const s=surface();if(ps.some(p=>!D.inside(p,s.boundary)))throw Error('Void vertices must be inside this surface.');update(()=>{s.holes||=[];s.holes.push(ps);});}else{const s={id:uid(),kind,boundary:ps,holes:[],label:(kind==='ceiling'?'Ceiling':'Floor')+' · explicit boundary',elevation_m:kind==='ceiling'?doc().wall_height_m:0,dimension_status:'assumed'};surfaceId=s.id;update(d=>d.surfaces.push(s));}drawing=null;h.render();}
function down(e){if(!active||h.is3d())return;const p=coords(e);if(faceOverview&&e.button===0){const id=e.target.closest('[data-design-wall]')?.dataset.designWall;if(id){const wall=doc().features.find(w=>w.id===id),side=D.roomWallSide(doc(),wall,roomRows.find(r=>r.id===roomId))??-1;const existing=data().surfaces.find(s=>s.wall_id===id&&s.side===side&&(!s.room_id||s.room_id===roomId));if(existing)changeSurface(existing.id);else{const sf={id:uid(),kind:'wall',wall_id:id,side,room_id:roomId,label:(roomRows.find(r=>r.id===roomId)?.name||'Room')+' · wall face',dimension_status:'assumed'};surfaceId=sf.id;faceOverview=false;update(d=>d.surfaces.push(sf));fit();}}return;}if(e.button===1||e.shiftKey&&e.button===2){gesture={pan:true,p,box:[...box],client:[e.clientX,e.clientY]};return;}if(e.button!==0)return;h.svg.focus();if(drawing){drawing.points.push(p);draw();inspector();return;}const s=surface();if(pendingKind&&s){addItem(pendingKind,local(s,p));pendingKind=null;return;}const hit=e.target.closest('[data-design-item],[data-design-resize]');if(!hit){const sf=e.target.closest('[data-design-surface]');if(sf&&sf.dataset.designSurface!==surfaceId){changeSurface(sf.dataset.designSurface);return;}selected.clear();draw();inspector();return;}const id=hit.dataset.designItem||hit.dataset.designResize,o=items().find(o=>o.id===id);if(!o)return;inspectorTab='items';if(e.shiftKey){selected.has(id)?selected.delete(id):selected.add(id);draw();inspector();return;}if(!selected.has(id))selected=new Set([id]);gesture={id,mode:editMode,resize:!!hit.dataset.designResize,p:local(s,p),before:D.copy(o),members:D.copy(selectedItems()),preview:D.copy(o),moved:false};h.svg.setPointerCapture(e.pointerId);draw();inspector();}
function move(e){if(!gesture)return;if(gesture.pan){const scale=box[2]/h.svg.clientWidth;box=[gesture.box[0]-(e.clientX-gesture.client[0])*scale,gesture.box[1]-(e.clientY-gesture.client[1])*scale,box[2],box[3]];draw();return;}
 const s=surface(),p=local(s,coords(e)),g=gesture,dx=p[0]-g.p[0],dy=p[1]-g.p[1];g.moved||=Math.hypot(dx,dy)>box[2]/h.svg.clientWidth*2;guides=[];
 if(g.resize){if(g.before.run)throw Error('Edit run vertices to resize this profile.');g.preview=D.resize(g.before,[dx,dy]);g.previews=[g.preview];}
 else if(g.mode==='rotate'){const a=Math.atan2(g.p[1]-g.before.y,g.p[0]-g.before.x),b=Math.atan2(p[1]-g.before.y,p[0]-g.before.x);let degrees=(b-a)*180/Math.PI;if(!e.altKey)degrees=Math.round(degrees/5)*5;const r=degrees*Math.PI/180;g.previews=g.members.map(o=>{const x=o.x-g.before.x,y=o.y-g.before.y;return {...o,x:g.before.x+x*Math.cos(r)-y*Math.sin(r),y:g.before.y+x*Math.sin(r)+y*Math.cos(r),rotation:o.rotation+degrees}});g.preview=g.previews.find(q=>q.id===g.id);}
 else{let x=dx,y=dy;const o={...D.copy(g.before),x:g.before.x+dx,y:g.before.y+dy};
 if(!e.altKey&&document.querySelector('#snap').checked){const scene=D.copy(doc());scene.surface_design.items=scene.surface_design.items.filter(q=>!selected.has(q.id));const snap=D.snap(scene,s,o,8*box[2]/h.svg.clientWidth);x+=snap.item.x-o.x;y+=snap.item.y-o.y;guides=snap.guides;}
 g.previews=D.translate(g.members,x,y);g.preview=g.previews.find(q=>q.id===g.id);}
 draw();}
function up(e){if(!gesture)return;const g=gesture;gesture=null;guides=[];if(h.svg.hasPointerCapture(e.pointerId))h.svg.releasePointerCapture(e.pointerId);if(g.moved&&g.previews)update(d=>{d.items=d.items.map(o=>g.previews.find(q=>q.id===o.id)||o);});else draw();}

function planOverlay(d,px){if(!d.surface_design||!d.calibration)return '';const m=d.calibration.metres_per_pixel,hidden=d.surface_design.hidden_categories||[];let html='<g id="surface-plan-overlay">';for(const o of d.surface_design.items){const s=d.surface_design.surfaces.find(s=>s.id===o.surface_id);if(!s||hidden.includes(s.kind)||hidden.includes(o.kind)||D.context(d,s).missing)continue;let pts;if(s.kind==='wall'){const xs=D.corners(o).map(p=>p[0]),min=Math.min(...xs),max=Math.max(...xs),a={...o,x:0,y:0,rotation:0};pts=[[min,0,0],[max,0,0],[max,0,o.depth],[min,0,o.depth]].map(([x,y,z])=>D.world(d,s,a,[x,y],z).slice(0,2).map(v=>v/m));}else pts=D.corners(o).map(p=>{const c=D.context(d,s);return p.map((v,i)=>(v+c.origin[i])/m);});html+=`<g data-plan-design="${o.id}" role="button" tabindex="0" aria-label="Design ${esc(labels[o.kind])}"><title>${esc(labels[o.kind])} · ${esc(s.label)} · placeholder</title><path d="${polygon(pts)}" fill="${palettes[o.kind]}" fill-opacity=".6" stroke="#627c8c" stroke-width="${px}" ${s.kind==='ceiling'?`stroke-dasharray="${4*px}"`:''}/></g>`;}return html+'</g>';}
function pick(hit){if(!active||!hit)return;const o=data().items.find(o=>o.id===hit.id),s=data().surfaces.find(s=>s.id===(o?.surface_id||hit.id));if(s){if(s.room_id)roomId=s.room_id;surfaceId=s.id;kind=s.kind;selected=new Set(o?[o.id]:[]);inspectorTab=o?'items':inspectorTab;faceOverview=false;h.viewer?.()?.faces.forEach(f=>f.selected=selected.has(f.id)||!selected.size&&f.id===surfaceId);h.viewer?.()?.draw();inspector();}}
function install(bridge){h=bridge;h.svg.addEventListener('pointerdown',e=>{const hit=e.target.closest('[data-plan-design]');if(!active&&hit){e.preventDefault();e.stopImmediatePropagation();open().then(()=>{pick({id:hit.dataset.planDesign});fit();h.render();});}},true);document.querySelector('#design-open').onclick=()=>active?close():open();
for(const [type,fn] of [['pointerdown',down],['pointermove',move],['pointerup',up]])h.svg.addEventListener(type,e=>{if(!active||h.is3d())return;e.stopImmediatePropagation();e.preventDefault();try{fn(e);}catch(err){cancel();h.toast(err.message);}},true);
h.svg.addEventListener('pointercancel',()=>{if(active)cancel();},true);h.svg.addEventListener('wheel',e=>{if(!active||h.is3d())return;e.preventDefault();e.stopImmediatePropagation();const p=coords(e),scale=box[2]/h.svg.clientWidth;if(e.ctrlKey){const f=Math.exp(Math.max(-200,Math.min(200,e.deltaY))*.01);box=[p[0]+(box[0]-p[0])*f,p[1]+(box[1]-p[1])*f,Math.max(.1,Math.min(200,box[2]*f)),Math.max(.1,Math.min(200,box[3]*f))];}else{box[0]+=e.deltaX*scale;box[1]+=e.deltaY*scale;}draw();},{capture:true,passive:false});
for(const [id,factor] of [['in',.8],['out',1.25],['fit',null]])document.querySelector('#'+id).addEventListener('click',e=>{if(!active||h.is3d())return;e.stopImmediatePropagation();if(factor){const cx=box[0]+box[2]/2,cy=box[1]+box[3]/2;box=[cx-box[2]*factor/2,cy-box[3]*factor/2,box[2]*factor,box[3]*factor];draw();}else fit();},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-design-action]');if(!b)return;e.stopImmediatePropagation();Promise.resolve().then(()=>action(b.dataset.designAction)).catch(err=>h.toast(err.message));},true);
document.addEventListener('change',e=>{if(!active)return;const key=e.target.dataset.designField,hidden=e.target.dataset.designHide;if(key||hidden){e.stopImmediatePropagation();e.target.setCustomValidity?.('');delete e.target.dataset.pendingEdit;try{if(hidden)update(d=>{d.hidden_categories=(d.hidden_categories||[]).filter(k=>k!==hidden);if(!e.target.checked)d.hidden_categories.push(hidden);});else change(key,e.target);}catch(err){e.target.setCustomValidity?.(err.message);h.toast(err.message);}}},true);
document.addEventListener('keydown',e=>{if(!active||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.metaKey||e.ctrlKey)return;if(h.is3d()&&e.target.tagName==='CANVAS')return;e.stopImmediatePropagation();if(e.key==='Escape'){e.preventDefault();cancel();selected.clear();h.render();}if(e.key==='Enter'&&drawing){e.preventDefault();try{finishBoundary();}catch(err){h.toast(err.message);}}if(['Delete','Backspace'].includes(e.key)&&selected.size){e.preventDefault();action('delete');}},true);
document.querySelector('#view2').addEventListener('click',e=>{if(!active)return;e.stopImmediatePropagation();h.mode('2d');fit();h.render();},true);
document.querySelector('#viewe').addEventListener('click',e=>{if(!active)return;e.stopImmediatePropagation();h.mode('2d');fit();inspector();},true);
}
window.SurfaceDesign={open,focus3d,viewerOptions:()=>({beginEdit:begin3d,moveEdit:move3d,endEdit:end3d,afterDraw:gizmo3d}),install,draw,inspector,pick,isSelected:id=>active&&(selected.has(id)||!selected.size&&id===surfaceId),planOverlay,active:()=>active,close,fit};
})();
