'use strict';
/* Staging-only transport. Production modules never receive a network API. */
(()=>{
 const nativeFetch=window.fetch.bind(window),base=new URL('.',document.currentScript.src),KEY='pixeloid.synthetic-ui.v2',CONFIG=KEY+'.controls',clone=structuredClone;
 const ready=nativeFetch(new URL('ui-fixtures.json?v=0c809d77a4ec',base)).then(r=>{if(!r.ok)throw Error('Synthetic fixtures unavailable');return r.json()});
 const multiReady=nativeFetch(new URL('multi-room-fixtures.json?v=962aa98b6c19',base)).then(r=>r.json());
 let settings;try{settings=JSON.parse(localStorage.getItem(CONFIG)||'{}')}catch{settings={}}
 settings={mode:'populated',save:'normal',delay:2000,...settings};
 const storageKey=()=>KEY+(settings.scenario==='multi-room'?'.multi-room':'');
 const seedFor=()=>settings.scenario==='multi-room'?multiReady:ready;
 const config=()=>({...settings});const configure=v=>{Object.assign(settings,v);localStorage.setItem(CONFIG,JSON.stringify(settings));window.dispatchEvent(new Event('staging-controls'))};
 async function load(){const seed=await seedFor();try{const s=JSON.parse(localStorage.getItem(storageKey())||'null');if(s?.version===2)return s}catch{}return {version:2,...clone(seed)}}
 function write(db){localStorage.setItem(storageKey(),JSON.stringify(db));window.dispatchEvent(new Event('staging-saved'))}
 const project=db=>db.state.projects['synthetic-ui'],room=(db,id)=>project(db).rooms.find(r=>r.id===id),fail=(text,status=400)=>{const e=Error(text);e.status=status;throw e};
 const shape=d=>JSON.stringify({features:d.features,calibration:d.calibration,surfaces:d.surface_design,height:d.wall_height_m});
 const wait=ms=>new Promise(r=>setTimeout(r,ms));
 async function gate(save=false){if(settings.mode==='disconnected')fail('SIMULATED disconnected. Reconnect using Testing controls. Your edits are kept.',503);if(settings.mode==='loading')await wait(settings.delay);if(save){if(settings.save==='delayed')await wait(settings.delay);if(settings.save==='rejected'){configure({save:'normal'});fail('SIMULATED rejected save. Edits remain unsaved; try again.',422)}if(settings.save==='conflict'){configure({save:'normal'});fail('SIMULATED revision conflict. Another browser edit won; reload saved data before retrying.',409)}}}
 function drawing(db,aid){const a=db.state.assets[aid],d=db.docs[a.manual_draft_id];return {units:d.units||'m',manual_draft_id:d.id,review:{},revision:d.revision,map_revision:project(db).map_revision,base_asset_id:null,elements:[],edits:{},features:clone(d.features),width:d.width,height:d.height,surface_design:clone(d.surface_design),site:{model:{metres_per_pixel:.01,wall_heights:{'Floor 1':2.8,'Floor 2':2.8},scale_source:'Synthetic dimensions; not surveyed'}}}}
 function scene(db,aid,rid){const d=db.docs[db.state.assets[aid].manual_draft_id],s=clone(db.scenes[d.id]),r=room(db,rid)||project(db).rooms.find(r=>r.plan_id===aid);s.floor=r.floor;s.saved_camera=Object.values(r.camera_views||{})[0]?.camera;s.simulated=true;s.static_fixture=true;return s}
 function blockResponse(db,r,items){const s=scene(db,r.plan_id,r.id);return {items:clone(items||r.block_layout.items),issues:[],revision:r.revision,basis:'synthetic',room_dimensions:{width_m:r.bbox[2]*db.state.assets[r.plan_id].width*.01,depth_m:r.bbox[3]*db.state.assets[r.plan_id].height*.01,height_m:2.8,source:'Synthetic fixture'},architecture:{study_reviewed:true,typed_wall_count:6,typed_opening_count:5,notes:['Mock checks only; no backend collision validation.']},preview_scene:s,preview_floors:[{room_id:r.id,scene:s}],drawing:drawing(db,r.plan_id)}}
 function invalidate(db,r){r.edit_revision_equivalents=[...(r.edit_revision_equivalents||[]),r.revision];r.revision++;r.view_approvals={};r.approved_image_id=null;r.approved_video_id=null}
 function advance(db){let changed=false;for(const j of Object.values(db.state.jobs)){if(!['queued','running','waiting'].includes(j.status))continue;const t=Date.now()/1000-j.created;j.status=t<2?'queued':'running';j.started=j.created+2;j.progress=Math.min(96,Math.round(t/18*100));j.progress_scope='sampling';j.steps=[Math.floor(j.progress/5),20];j.stage='SIMULATED · '+(t<2?'queued':'processing bundled fixture');if(t>=18){if(j.outcome==='failure'){j.status='failed';j.error='SIMULATED failure. Use Recover to replay this local job.';j.stage='SIMULATED · failed'}else{j.status='completed';j.progress=100;j.finished=Date.now()/1000;j.stage='SIMULATED · sample ready';const r=room(db,j.room_id),source=db.state.assets[j.kind==='video'?'video-1':'image-1-2'],id='sample-'+j.id;const a={...clone(source),id,room_id:r.id,view_id:j.view_id||Object.keys(r.camera_views)[0],view_revision:r.camera_views[j.view_id||Object.keys(r.camera_views)[0]]?.revision||1,input_revision:r.revision,parent_id:j.parent_id||r.images.at(-1),source_image_id:j.source_image_id,status:'review',created:j.finished,job_id:j.id,review_note:'SIMULATED bundled sample. No inference or backend validation.'};db.state.assets[id]=a;r[j.kind==='video'?'videos':'images'].push(id);j.result_asset_id=id}}changed=true}if(changed)write(db)}
 function makeJob(db,r,kind,data={}){const id='sim-'+crypto.randomUUID(),now=Date.now()/1000,j={id,project_id:'synthetic-ui',room_id:r.id,view_id:data.view_id||Object.keys(r.camera_views)[0],kind,status:'queued',stage:'SIMULATED · queued',created:now,submission_intent:now,progress:0,progress_scope:'sampling',outcome:settings.mode==='failure'?'failure':'success',source_image_id:r.view_approvals?.[data.view_id]?.approved_image_id||r.approved_image_id,video_preset:data.preset||data.video_preset||'ltx-preview-768x432-2s-v1',duration:Number(data.duration)||2,motion:data.motion||'still',parent_id:r.scene_control?.source_id||r.images.at(-1),simulated:true};db.state.jobs[id]=j;write(db);return clone(j)}
 async function api(path,data={},method='POST'){
  const u=new URL(path,location.href),p=u.pathname,read=method==='GET';let db=await load();const epoch=db.epoch,namespace=storageKey();
  if(p==='/api/state'){if(settings.mode==='loading')await wait(settings.delay);if(settings.mode!=='disconnected')advance(db);db.state.engine={connected:settings.mode!=='disconnected',remote:false,running:Object.values(db.state.jobs).filter(j=>j.status==='running').length,pending:0};return clone(db.state)}
  const isSave=!read&&!p.endsWith('/camera-preview')&&!(p.endsWith('/blocks')&&['check','propose','suggest'].includes(data.action))&&!p.endsWith('/prepare-edit');await gate(isSave);db=await load();if(db.epoch!==epoch||storageKey()!==namespace)fail('Synthetic data was reset during this request. Reopen the workspace.',409);
  let m=p.match(/^\/api\/projects\/synthetic-ui\/plans\/(plan-[12])\/(drawing|shared-scene|camera-preview|floor-camera)$/);
  if(m){const [,aid,action]=m,r=room(db,data.room_id||u.searchParams.get('room_id'))||project(db).rooms.find(r=>r.plan_id===aid);
   if(action==='drawing')return drawing(db,aid);
   if(action==='shared-scene')return scene(db,aid,r.id);
   if(action==='camera-preview')return {image:'/ps/samples/room-v1.png',typed_segments:true,objects:[{label:'STATIC synthetic camera fixture — not a live rebuild',color:'#7c9891',status:'SIMULATED'}],simulated:true};
   if(action==='floor-camera'){if(data.revision!==r.revision)fail('Synthetic room revision conflict; reload camera.',409);const id=data.view_id||'view-'+crypto.randomUUID(),old=r.camera_views[id];if(old&&data.view_revision!==old.revision)fail('Synthetic camera revision conflict.',409);const camera=Object.fromEntries(['position','target','height','target_height','horizontal_fov'].map(k=>[k,data[k]]));const v={id,name:data.view_name||'New view',revision:(old?.revision||0)+1,camera};r.camera_views[id]=v;r.view_approvals[id]={};write(db);return {revision:r.revision,camera,view:v}}
  }
  m=p.match(/^\/api\/projects\/synthetic-ui\/rooms\/(room-[12](?:-[a-z0-9]+)?)(?:\/(.+))?$/);
  if(m){const r=room(db,m[1]),action=m[2];if(!r)fail('Synthetic room not found',404);
   if(action==='blocks'){
    if(data.revision!==r.revision)fail('Synthetic revision conflict. Reload saved plan.',409);
    if(data.action==='save-plan'||data.action==='save'){
     const drafts=data.drafts||[{room_id:r.id,revision:r.revision,items:data.items,reviewed:data.reviewed}];for(const d of drafts){const rr=room(db,d.room_id);if(!rr||rr.revision!==d.revision)fail('Synthetic revision conflict. Reload plan.',409)}
     for(const d of drafts){const rr=room(db,d.room_id);rr.block_layout={items:clone(d.items),reviewed:!!d.reviewed};invalidate(db,rr)}
     write(db);
    }
    return blockResponse(db,r,data.items);
   }
   if(action==='prepare-edit')return {prompt:'SIMULATED edit instructions: '+(data.instruction||'Change selected object')+'. No model or backend will run.'};
   if(action==='scene-control'){r.scene_control=clone(data);r.edit_revision++;write(db);return r}
   if(action==='generate-image'||action==='generate-video')return makeJob(db,r,action.endsWith('video')?'video':'image',data);
   if(action==='reference'){r.references=r.references.filter(id=>id!==data.asset_id);write(db);return r}
   if(['approve-image','approve-video','reject-image','reject-video','keep-image'].includes(action)){
    const a=db.state.assets[data.asset_id];if(!a||a.room_id!==r.id)fail('Synthetic asset not found');const kind=a.kind,approve=action.startsWith('approve'),reject=action.startsWith('reject');a.review_history||=[];a.review_history.push({status:a.status,decision:a.review_decision,note:a.review_note||'',recorded_at:new Date().toISOString()});a.status=approve?'approved':reject?'rejected':'review';a.review_note=approve?'Approved.':reject?(data.reason||'Needs revision'):'Kept for review — not approved.';a.review_decision=approve?'approved':reject?'rejected':'kept';r.view_approvals[a.view_id]||={};if(approve){r['approved_'+kind+'_id']=a.id;r.view_approvals[a.view_id]['approved_'+kind+'_id']=a.id}else{if(r['approved_'+kind+'_id']===a.id)r['approved_'+kind+'_id']=null;if(r.view_approvals[a.view_id]['approved_'+kind+'_id']===a.id)delete r.view_approvals[a.view_id]['approved_'+kind+'_id']}write(db);return a
   }
   if(!action&&method==='PATCH'){Object.assign(r,data);write(db);return r}
  }
  m=p.match(/^\/api\/jobs\/([^/]+)\/(cancel|recover)$/);if(m){const j=db.state.jobs[m[1]];if(!j)fail('Synthetic job not found',404);if(m[2]==='cancel'){j.status='cancelled';j.stage='SIMULATED · cancelled';j.finished=Date.now()/1000}else{j.status='queued';j.stage='SIMULATED · reconnected to same local job';j.created=Date.now()/1000;j.progress=0;j.outcome='success';delete j.error;delete j.finished}write(db);return j}
  m=p.match(/^\/api\/assets\/([^/]+)(?:\/(revision-comparison))?$/);if(m){const a=db.state.assets[m[1]];if(!a)fail('Synthetic asset not found',404);if(!m[2]){if(method==='PATCH'){Object.assign(a,data);write(db)}return a}const r=room(db,a.room_id),parent=db.state.assets[a.parent_id]||db.state.assets[r.images[0]],ref=db.state.assets[r.references[0]];return {status:a.status,review_decision:a.review_decision,parent,result:a,reference:ref?{...ref,label:ref.category,crop:[0,0,512,512]}:null,parent_note:'Bundled synthetic parent; no generation provenance',reference_note:'Bundled synthetic reference',outline:[[1120,480],[1760,480],[1760,820],[1120,820]],crop:[1000,350,820,600]}}
  fail('Unavailable in staging: this action has no browser mock. No request was sent.',404);
 }
 async function planApi(path,body,raw=false){if(raw)fail('Use a bundled synthetic reference. Private uploads are disabled.');const epoch=(await load()).epoch,namespace=storageKey();await gate(body!==undefined&&path!='/resolve'&&path!='/preview');const db=await load();if(db.epoch!==epoch||storageKey()!==namespace)fail('Synthetic data was reset during this request.',409);if(path==='')return Object.values(db.docs).map(d=>({id:d.id,name:d.name,revision:d.revision,count:d.features.length}));const key=path.slice(1);if(db.docs[key]){if(body===undefined){const a=Object.values(db.state.assets).find(a=>a.manual_draft_id===key),r=project(db).rooms.find(r=>r.plan_id===a.id);const selectionKey='pixeloid-ui-staging-selection:synthetic-ui';let saved={};try{saved=JSON.parse(localStorage.getItem(selectionKey)||'{}')}catch{}if(saved.planId!==a.id)localStorage.setItem(selectionKey,JSON.stringify({...saved,planId:a.id,roomId:r.id,floor:r.floor,cameraId:Object.keys(r.camera_views)[0]||null}));return clone(db.docs[key]);}if(body.revision!==db.docs[key].revision)fail('Synthetic revision conflict. Reopen saved draft.',409);if(!Array.isArray(body.features)||body.features.some(f=>!f.points?.flat().every(Number.isFinite)))fail('Invalid synthetic coordinates');const d={...clone(body),revision:body.revision+1};db.docs[key]=d;const a=Object.values(db.state.assets).find(a=>a.manual_draft_id===key);a.manual_document=d;a.drawing={revision:d.revision};project(db).map_revision++;for(const r of project(db).rooms.filter(r=>r.plan_id===a.id))invalidate(db,r);write(db);return clone(d)}
  if(path==='/preview'){const seed=(await seedFor()).docs[body.id];if(shape(body)!==shape(seed))fail('Live geometry rebuilding is unavailable. Save your 2D edits; the original 3D fixture is static.');return clone(db.scenes[body.id])}
  if(path==='/resolve')return window.StagingJoinedFootprints.resolve(body.features);
  fail('Unsupported staging action. No backend request sent.',404)
 }
 window.fetch=async(input,options={})=>{const u=new URL(typeof input==='string'||input instanceof URL?input:input.url,location.href);if(u.origin!==location.origin)return new Response('{"error":"External requests disabled in staging"}',{status:403});if(u.pathname.startsWith('/api/')){try{return new Response(JSON.stringify(await api(u.href,options.body?JSON.parse(options.body):{},options.method||'GET')),{headers:{'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:e.message}),{status:e.status||400,headers:{'Content-Type':'application/json'}})}}if(u.pathname==='/furniture-meshes.json')return nativeFetch(new URL('furniture-meshes.json',base));if(u.pathname.startsWith('/ps/'))return nativeFetch(input,options);return new Response('{"error":"Not available in synthetic staging"}',{status:404})};
 async function reset(mode='populated'){const db={version:2,...clone(await seedFor()),epoch:crypto.randomUUID()};if(mode==='empty'){for(const r of project(db).rooms){r.block_layout.items=[];r.images=[];r.videos=[];r.references=[];r.camera_views={};r.view_approvals={};r.approved_image_id=null}for(const d of Object.values(db.docs)){d.features=[];d.surface_design={version:1,surfaces:[],items:[]}}}write(db);configure({mode});if(mode==='success'||mode==='failure'){const r=project(db).rooms[0],j=makeJob(db,r,'video');db.state.jobs[j.id]={...j,created:Date.now()/1000-20,outcome:mode};advance(db)}return db}
 window.Staging={selectScenario:async scenario=>{configure({scenario,mode:'populated'});return load()},ready,load,write,api,planApi,shape,config,configure,reset,reference:async()=>({image:'/ps/samples/'+(settings.reference||'art')+'.png',image_width:512,image_height:512,source_name:'Bundled synthetic '+(settings.reference||'art'),dimension_status:'assumed',aspect_locked:false})};
})();
